### ISSUE TITLE
Bug : faker 를 @faker-js/faker 로 교체

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#104]
@axisotherwise  @unchaptered 

### 한 일

기존에 가짜 데이터 생성과 관련되 ***faker v5.5.3*** 라는 라이브러리를 사용했습니다.
하지만, 과거 업로드한 사람이 ***faker v6.6.6*** 라는 버전에서 모든 정보를 지우는 이슈로 이후로 관리가 제대로 안되고 있습니다.
따라서, ***@types/faker*** 가 지원이 되지 않고 있어서 TypeScript 에서 사용 할 수가 없었습니다.

그래서 대체제인 ***@faker-js/faker*** 를 찾아서 설치하였습니다.
주소 ***https://fakerjs.dev/guide/***

- 삭제 항목

```json
"@types/faker": "^6.6.9"
"faker": "^5.5.3"
```

- 추가 항목

```json
"@faker-js/faker": "^7.5.0",
```

### 조치 사항

만약 조치한 것이 있거나 구글링한 게 있다면, ...

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
너무나도 유용한 faker~~
