### ISSUE TITLE
Bug : Jest has detected the following 2 open handle potentially keeping Jest from exiting

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#105]
### 한 일

E2E 테스트를 위해서 다음과 같이 ***npm run test:e2e*** 를 실행했습니다.

```json
"test:e2e": "cross-env NODE_ENV=test jest --runInBand --detectOpenHandles --findRelatedTests test/e2e/ --silent"
```

- ***runInBand*** : 모든 테스트를 TopDown 방식으로 순차 실행을 합니다.
- ***detectOpenHandles*** : 열려 있는 PORT 나 PoolConnection 을 감지해서 알려줍니다.
- ***findRelatedTest*** : 실행하기 위한 적은 파일들을 설정한다. (해당 부분은 체크해서 불필요하면 제거하도록 하겠습니다.)

### 에러 내용

```cmd
Jest has detected the following 2 open handle potentially keeping Jest from exiting:
```

총 2 개의 Open Handle 이 감지되었고 이를 닫을 수 있게 코드를 바꿔야 합니다.

- ***http.Server*** 인스턴스
- ***mysql2/promise.PoolConnection*** 인스턴스

### 조치 사항

감지되는 지점의 코드는 다음과 같습니다.

```typescript
export class App {

    /* 기존의 코드 */

    runServer(MODE: TNODE_ENV, PORT: number): Server {
        return App.app.listen(PORT, () => {
            if (MODE !== "test") console.log(`Server is running on ${PORT} with ${MODE} MODE`);  //  < Detected Open Handle
        });
    }
}
```

```typescript
export class MysqlProvider {
    /** @throws { CustomException } */
    public getConnection = async () => {
        this.validateIsInit();

        try {
            return await MysqlProvider.pool.getConnection();  //  < Detected Open Handle
        } catch (err) {
            throw this.errorHandler(err);
        }
    };
}

```

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
## 조치사항 1 - MySQL2/promise.PoolConnection

DB 를 사용하는 방식이 ***Pooling*** 이기 때문에, Pool 을 만들고 나서 바로 ***PoolConnection*** 을 확인해야 했습니다. 따라서, 다음과 같은 코드를 실행하고 있었습니다.

```typescript
static validateConnetion = async (pool: mysql.Pool) => {
        try {
            const poolConnection: mysql.PoolConnection = await pool.getConnection();
        } catch (err) {
            throw err;
        }
    };

```

위 코드에서 poolConnection 을 제거하지 않았기 때문에 ***Open Handle*** 상태로 감지되었습니다.
따라서, 다음과 같이 변경하여 에러를 해결하였습니다.

```typescript
static validateConnetion = async (pool: mysql.Pool) => {
        try {
            const poolConnection: mysql.PoolConnection = await pool.getConnection();
            poolConnection.destroy();
        } catch (err) {
            throw err;
        }
    };

```

**Comment by unchaptered** [comment]
## 조치사항 2 -http.Server

기본적으로 express 코드는 다음과 같습니다.

```typescript
import * as epresss from "express':
import * as http from "http";

const app: express.Application = express();
const server: http.Server = app.listen(3000, () => console.log("Server is running on 3000 port");
```

포트가 열리는 구간인 ***app.listen*** 은 nodejs 내장 모듈인 ***http.Server*** 을 반환하는 메서드입니다.
따라서 해당 메서드의 반환값을 저장 해두고 이를 ***http.Server.close()*** 해주어야 합니다.

하지만, 기존의 코드는 다음과 같이 구성되어 있습니다.

```typescript
export class App {

    app: express.Application;

    constructor(MODE: TNODE_ENV, PORT: number, CORS_ORIGIN_LIST: string[]) {
        this.app = express();

        this.setMiddleware(MODE, CORS_ORIGIN_LIST);
        this.setRouter();
        this.runServer(MODE, PORT);
    }

}
```

이 부분의 app 을 static 인자로 변환하고 다음과 같이 변경하였습니다.
기존에 생성자 안에 있던 ***this.runServer(MODE, PORT)*** 구문을 외부에서 호출하게 변경하였습니다.

```typescrpt
export default class App {
    static app: express.Application;

    constructor(MODE: TNODE_ENV, CORS_ORIGIN_LIST: string[]) {
        App.app = express();

        this.setMiddleware(MODE, CORS_ORIGIN_LIST);
        this.setRouter();
    }
}
```

**Comment by axisotherwise** [comment]
**조치사항 1 - MySQL2/promise.PoolConnection**
**Connection** 대여 후 **release**를 하지 않아  발생한 **Connection Leak** 에러로 인지했는데 **Connection** 자체를 해제하지 않아 발생하는 에러였네요. **destroy** 메서드는 처음 보는 기능인데 조금 더 알아봐야겠습니다. 감사합니다!

**Comment by unchaptered** [comment]
> **조치사항 1 - MySQL2/promise.PoolConnection** **Connection** 대여 후 **release**를 하지 않아 발생한 **Connection Leak** 에러로 인지했는데 **Connection** 자체를 해제하지 않아 발생하는 에러였네요. **destroy** 는 사용해 본 적 없는 메서드인데 데이터베이스와의 연결을 해제하는 메서드인가 보네요. 조금 더 알아봐야겠습니다. 감사합니다!

넵, 그리고 이 해당 부분은 현재 ***MysqlProvider.prototype.validateConnetion*** 내부에서 createPool() 을 하고 해당 포트를 닫지 않아서 생기는 문제입니다.

relaese 를 했을 때에도, 포트가 정확히 닫지는 지는 차후에 통합 테스트를 작성할 때 확인해보면 될 것같습니다.

> + 추가적으로 이 이슈에 대한 코드는 현재 ***test/e2e*** 에 있습니다.

**Comment by unchaptered** [comment]
E2E 테스트에 대한 별다른 작업이 진행되지 않아서, 이슈를 닫겠습니다.
