### ISSUE TITLE
2차 기술 피드백 - 백엔드

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#107]
## [2차 기술 멘토링 기록] 백엔드
---
**멘토링 일자** : 9월 9일 금, 14:35 ~ 15:00
**멘토링 위치** : 파도 테이블
**멘토님** : 최지헌 멘토님
**노션 링크** : [2차 기술 멘토링 사전 노트 (3조)](https://global-giraffe-ef7.notion.site/2-3-_-0909-3b34dec6c04b475d955df46e731a78c0)

## 총괄 정리

추가적으로 다음 주에 있는 ***MVP 중간 발표*** 를 대비해서, 다음 내용을 보완하는 것에 대한 이야기가 있었습니다.
더 자세한 내용은 ***[노션 문서](https://www.notion.so/2-3-_-0909-3b34dec6c04b475d955df46e731a78c0#5dd0b188180a4e47843f529a704e6fed)*** 를 참고해주세요.

1. 라이브러리 선택 기준
2. 기술 선택 이유
3. 피드백 받고 개선한 부분

---

## 프론트엔드

[2차 기술 피드백 - 프론트엔드](https://github.com/cupicks/cupicks-fe/issues/48)

### 1. 이미지 리사이징 Lambda 의 구현 방향

S3 버킷에 이미지를 ***프로필 사진*** 과 ***댓글 사진*** 와 같이 2 종류를 올리고 있습니다.
해당 이미지를 Lambda 의 ***이미지 리사이징 코드*** 를 통해서 처리해주고 있는데요. 이미지 대상이 2 개로 늘어남에 따라서 다음의 선택지가 고민이 됩니다.

1. 이미지 최초 저장 시점부터, 경로를 구분하지 않고 1개의 폴더에 저장 후 ***트리거 (Prefix)*** 를 통해서 함수 내에서 프로필과 코멘트를 구분하여 분기 처리
4. 이미지 별로 Lamda 를 등록하는 방법 각각의 이미지에 대한 람다를 처리하는 방식

####  ❗ 답변

👉 ***Lambda*** 를 2 개 이용하기 보다는 분기처리 를 하는 것이 일반적이다.
👉 역할이 동일하기 때문에, 굳이 2개를 만드는 것은 불필요할 것 같습니다.

---

### 2. package.json script 에서의 tsc 미작동 이슈

로컬환경에서 터미널에 직접 ***tsc*** 를 입력했을 때에는 컴파일이 정상적으로 진행이 됩니다.
하지만 ***package.josn*** 의 script 에서 ***tsc*** 를 호출하면 ***[[(Issue)his is not the tsc command you are looking for](https://github.com/cupicks/cupicks-be/issues/94)](https://github.com/cupicks/cupicks-be/issues/94) 이***라는 에러가 발생합니다.

1. 로컬환경 프로젝트 내부에 ***tsc***, ***typescript** 설치 완료              → 에러 최초 발견 지점*
2. 로컬환경 글로벌 영역에 ***typescript*** 설치 완료, ***tsc*** 설치 X      → 그냥 tsc가 돌아감 (???)
5. 배포환경 프로젝트 내부에 ***tsc, typescript*** 설치 완료              → 동일한 에러 발생
6. 배포환경 글로벌 영역에 ***typescript, tsc*** 설치 X                       → 명령어를 찾을 수 없다는 에러가 뜸 (기대와 동일)

따라서 지금 서버 배포할 때마다 ***tsc-watch*** 를 포함하고 있는 ***npm run start:dev*** 를 통해서 컴파일을 시키고 나서 서버를 키고 있습니다.
어떤 지점에서 컴파일이 실패하는 건지 이해할 수 없어서 질문을 남깁니다.

- **F반 최지현 멘토님 질의응답 페이지 :** [**[Bug : This is not the tsc command you are looking for](https://www.notion.so/Bug-This-is-not-the-tsc-command-you-are-looking-for-ec7300ddea9d4b39b93b60229b9696d6)**](https://www.notion.so/Bug-This-is-not-the-tsc-command-you-are-looking-for-ec7300ddea9d4b39b93b60229b9696d6)

####  ❗ 답변

👉 현재 tsc 가 안되는 문제를 구글링해보면, 버전 문제 혹은 글로벌 인스톨 의 문제로 분류가 되는 것 같습니다. 따라서, typescript 를 다른 버전으로 마이그레이션 하시거나, 아니면 글로벌 인스톨 하도록 해주세요.
👉 https://stackoverflow.com/questions/67677320/this-is-not-the-tsc-command-you-are-looking-for

---

####  ❗ 답변
👉 너무 좋은 것 같습니다.
👉 다만 어떤 ***번들러*** 에서 고민을 했고 어떤 것을 고르게 되었는지 등의 스토리가 보완되면 좋을 것 같습니다.

---

### 4. 싱글턴 보증의 한계 극복

싱글턴 보증으로 서버 코드를 짜도, Ctrl + S 를 여러번 누르면 서버가 포트 충돌 이 나서 꺼지던데, 보완할 수 있는 방법이 있을까요?

####  ❗ 답변

👉 이 방법을 보완 하거나 예방 할 수 있는 방법은 없는 것 같습니다.
👉 실제로 Ctrl + S 를 여러번 누르는 상황이 일어나는 경우가 별로 없어서 큰 걱정을 하지 않아도 될 것 같습니다.

---

### 5. pm2 환경변수 테스트

현재 ***배포 / 개발 / 테스트*** 환경 별로 다른 변수를 사용하고 있습니다.

배포 시에는 프로세스 매니저인 ***PM2*** 를 실행주체로 가지지만, 나머지 두 환경에서는 ***Node*** 혹은 ***Jest*** 라는 실행 주체를 가지고 있습니다.

이에 따라서, 테스트 코드에서 ***PM2.env_production*** 의 값이 없어서 ***환경변수 공급 시스템*** 을 테스트할 수 없는 문제가 있습니다. 해당 부분을 테스트할 수 있는 방법이 있을까요?

####  ❗ 답변

👉 테스트 할 수 없는 부분의 테스트 코드를 지우시거나, 실행 주체를 하나로 통일하는 것이 좋을 것 같아 보입니다.
👉 하지만, 실행 주체를 하나로 통일하는 것이 어렵다면 ***테스트 코드 삭제 를 고려*** 해보시는 것이 좋을 것 같습니다.

**Comment by axisotherwise** [comment]
1~5번 피드백 확인했습니다!

**Comment by unchaptered** [comment]
> 1~5번 피드백 확인했습니다!

넵!! 😀😀
