### ISSUE TITLE
Reqeust : 이메일 & 닉네임 인증 취소

### ISSUE THREAD

**Issue by dusunax** [cupicks/cupicks-be#115]
### 제안사항

@unchaptered 

사용자가 이메일 인증 요청, 이메일 인증, 닉네임 중복확인 후,
회원가입 페이지를 나가거나,
인증 내용을 변경하기 위해 회원가입을 처음부터 다시 시작할 때
인증 요청이나 인증 내용(토큰)을 서버에서 삭제해야 할 필요가 있습니다.

현재 해당 내용을 중복으로 요청할 경우
이미 인증 완료되었다는 에러가 나옵니다.

FE 해당 이슈 링크입니다.  
https://github.com/cupicks/cupicks-fe/issues/55

### **이메일 인증 요청, 이메일 인증, 닉네임 중복확인 관련 API** 
- 이메일 중복확인 후 인증 
  - GET `/api/auth/send-email?email=`
- 이메일에 도착한 숫자 확인
  - GET `/api/auth/confirm-email?email=이메일&email-verify-code=123456`
- 닉네임 중복확인 
  - GET `/api/auth/confirm-nickname?email=이메일&nickname=닉네임`

**Comment by unchaptered** [comment]
회원가입 절차는 step 1,2,3 로 이루어져 있는데 step 2 를 완료한 사용자는 step 1 을 하지 못하게 막아두었습니다.
해당 부분을 수정해놓겠습니다.

**Comment by unchaptered** [comment]
해당 내용이 모두 반영되었습니다.
