### ISSUE TITLE
Reqeust : 사용자 최대 이메일 발송횟수 제한

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#116]
> 구현이 완료 되었으나, 세부적인 에러가 발생할 수 있으나 전체 로직에 유의미한 값은 아닙니다.
> 차후에 보완해서 다시 푸쉬하겠습니다.

### 제안사항

현재 이메일 발송 서비스는 ***AWS SES*** 를 사용하고 있습니다.
메일 발송료가 ***0.1 $ / 1,000 mail*** 이기 떄문에, 사용자 `1일 당 최대 발송 횟수` 를 제한하고 싶습니다.
현재 도메인에서는 다음과 같은 경우에 메일 발송을 사용하고 있습니다.

1. 이메일 중복확인 후 인증번호 발송
2. 초기화 비밀번호 발송

해당 도메인에 ***1일 당 5회*** 발송 제한을 걸려고 하기 때문에 user_verify_list 와 user 테이블을 다음과 같이 변경해야 합니다.

```sql
CREATE TABLE IF NOT EXISTS user_verify_list (
    -- 다른 칼럼
    limited_email_count                                  INT             NULL, -- 1 일일 당 5 회만 가능
    limited_email_overflow_date                          DATETIME        NULL, -- 오버 플로우 시, 1일 간 사용 불가,
    is_overflowed_email                                  BOOLEAN         DEFAULT 0,
    -- 다른 칼럼
);
CREATE TABLE IF NOT EXISTS user (
    -- 다른 칼럼
    limited_send_passsword_count                       INT          NULL, -- 1 일일 당 5회만 가능
    limited_send_passsword_overflow_date               DATETIME     NOT NULL, -- 오버 플로우 시, 1일 간 사용 불가
    is_overflowed_send_password                        BOOLEAN      DEFAULT 0,
    -- 다른 칼럼
);
```

자세한 내용은 ***[3차 테이블 쿼리문](https://www.notion.so/3-_-0911-4d96ee29733c43c59e63cc99af49ef74)*** 를 참고해주세요.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
네 확인했습니다.

**Comment by unchaptered** [comment]
@wonseok-do @axisotherwise @dusunax  @cmun2 

> 성공했을 때의 메세지는 기본적으로 유지 된 채, 두 가지 도메인에 각각 할당된 일일 5 회 제한이 초과 되었을 떄의 메세지 유형이 생겨났습니다.
> 해당 상황에서 메일 발송은 이루어지지 않으며 frontend 쪽으로만 리턴 메세지가 발송됩니다.

- 이메일 중복확인 및 인증번호 횟수 초과 시,

![image](https://user-images.githubusercontent.com/86306802/189574011-56a4d82f-6744-4894-a4fc-d1eb81927d12.png)

- 비밀번호 재발급 횟수 최과 시,

![image](https://user-images.githubusercontent.com/86306802/189574017-2ef12dac-73ca-4be8-b21d-4c3a997d5194.png)

**Comment by unchaptered** [comment]
@wonseok-do @axisotherwise @dusunax  @cmun2 

> 성공했을 때의 메세지는 기본적으로 유지 된 채, 두 가지 도메인에 각각 할당된 일일 5 회 제한이 초과 되었을 떄의 메세지 유형이 생겨났습니다.
> 해당 상황에서 메일 발송은 이루어지지 않으며 frontend 쪽으로만 리턴 메세지가 발송됩니다.

- 이메일 중복확인 및 인증번호 횟수 초과 시,

![image](https://user-images.githubusercontent.com/86306802/189574011-56a4d82f-6744-4894-a4fc-d1eb81927d12.png)

- 비밀번호 재발급 횟수 최과 시,

![image](https://user-images.githubusercontent.com/86306802/189574017-2ef12dac-73ca-4be8-b21d-4c3a997d5194.png)
