### ISSUE TITLE
Reqeust : `vite` 를 사용한 성능 최적화

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#128]
### 제안사항

@axisotherwise 

***Ctrll + S*** 를 누르거나 서버 실행 하면, ***5초 ~ 20초*** 씩 실행 시간이 걸리고 있습니다.
***tsc*** 나 ***tsc-watch*** 라는 친구가 변환 속도가 너무 느린 것이 큰 문제인 것 같습니다.

roolup 방식으로 번들링을 하는 vite 를 사용하는 것으로 변경해서 속도를 최적화 할 시기가 된 것 같습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
vite는 프론트에서만 사용하는 걸로 알고 있었는데 제안해 주신 데로 서버 개발 환경에 도움이 된다면 도움해도 좋을 거 같습니다!

**Comment by unchaptered** [comment]
- 참고 자료 : https://github.com/axe-me/vite-plugin-node
