### ISSUE TITLE
Reqeust : 서버 설정 및 배포 자동화 필요성

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#129]
### 제안사항

@axisotherwise 

현재 배포 할 때마다, ssh 를 통해서 접속을 하고 있는데 ***5분 ~ 10분*** 씩 소모되는 것 같습니다.
프론트엔드 작업 집중하고 있는 기간 동안 시간 적인 여유가 있으니, 현재 작업해두는 것이 어떤가 합니다.

해당 작업 진행하면서 nginx 를 통해서 서버를  https 로 만드는 것도 병행하면 될 것 같습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
네 현재 기능 구현이 어느 정도 마무리된 거 같으니 진행하면 좋을 거 같습니다.
