### ISSUE TITLE
Bug : CodeDeploy - Process completed with exit code 254.

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#130]
### 한 일
@axisotherwise @unchaptered 

CICD 2차 시도 중에 에러가 발생했습니다.

### 에러 내용

```cmd
An error occurred (DeploymentLimitExceededException) when calling the CreateDeployment operation:
The Deployment Group '배포그룹명 (id=배포그룹 고유식별자)'
already has an active Deployment '배포 고유식별자'
Error: Process completed with exit code 254.
```

- Create CICD, try 2  https://github.com/cupicks/cupicks-be/actions/runs/3043005679/jobs/4901795082

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
https://www.daleseo.com/github-actions-jobs/

**Comment by unchaptered** [comment]
## IAM 생성

### 🎈 IAM + CodeDeploy

- IAM ROLE 생성하기 1
- 연결하는 장소는 CodeDeploy 의 ***애플리케이션 - 배포 그룹 생성*** 단계에서 적용 

![image](https://user-images.githubusercontent.com/86306802/189864413-4ccffab5-f174-4d2b-a08c-b3157fb328a6.png)
![image](https://user-images.githubusercontent.com/86306802/189864443-f9c59d0e-85d2-47ee-9f4b-47a8eb3621be.png)

### 🎈 IAM + EC2 

- IAM ROLE 생성하기 2
- 연결하는 장소는 CodeDeploy 의 ***EC2 생성 단계***  혹은 ***수정 단계***  IAM 역할 부여

![image](https://user-images.githubusercontent.com/86306802/189864811-936e600a-0795-4ddd-b2a1-4e75e01e4129.png)
![image](https://user-images.githubusercontent.com/86306802/189864856-7f152a1e-f83e-499d-b7e5-4514ff68ae06.png)

### S3

S3 에서는 추가 설정이 필요 없습니다.
