### ISSUE TITLE
Reqeust : Lambda 동시성에 따른 제안

### ISSUE THREAD

**Issue by axisotherwise** [cupicks/cupicks-be#133]
### 제안사항
@unchaptered 

제안 하고 싶은 내용
- Issue #99 
- Issue #107 
- Issue #108

위 이슈의 기술 피드백을 토대로 추가 자료를 찾아보니 **Lambda** 함수의 2가지의 동시성에 대해 알게 되었습니다.
<br>
1. **예약된 동시성** **(Reserved Concurrency)**
함수에 대한 최대 동시 인스턴스를 보장하며 한 함수가 동시성을 예약하면 다른 함수는 해당 동시성을 사용할 수 없습니다.

2. **프로비저닝된 동시성** **(Provisioned Concurrency)**
함수의 호출에 즉시 응답할 준비가 되도록 요청된 수의 실행 환경을 초기화합니다. 
프로비저닝 동시성을 구성하면 요금이 부과됩니다.
<br>

**Lambda** 함수는 기본적으로 동시에 **1,000** 개까지 실행할 수 있다고 합니다.
또한 최대 동시성을 개별 **Lambda 함수** 별로 함수가 동시에 실행할 수 있는 개수를 별도로 지정할 수 있습니다.
프로젝트는 이미지 리사이징 **요청 비중** 이 많은 건 아니지만 혹시라도 **1,000** 번 이상의 **요청** 이 동시에 들어온다면 
기능에 문제가 생길 수 있을 거 같습니다.  이러한 **예외 케이스** 를 커버하고 **함수 호출 수** 만큼 비용이 부과되는 
과금 체계를 고려해 **2개의 Lambda** 함수를 도입하는 방법을 제안 드립니다.
감사합니다!
<br>

### 환경 설정
```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
너무 좋은 것 같습니다!

**Comment by axisotherwise** [comment]
2018년 1월 업데이트 이후 Lambda 의 동시성이 **3,000회** 로 증가되었다고 합니다.
다만, **_자동 증가_** 가아닌 **_자동 승인_** 방식이므로 필요 시 **Support Case** 를 등록하면 3,000회 로 승인해 준다고 합니다! 
<br>
- [보다 강력한 Serverless] https://www.youtube.com/watch?v=X4_dhziSW6A
