### ISSUE TITLE
회원가입(이메일 인증번호 만료시간 오류)

### ISSUE THREAD

**Issue by wonseok-do** [cupicks/cupicks-be#134]
### 에러 내용
회원가입에서 이메일 인증번호 만료시간이 3분으로 되어있는데 3분지나고 나서 인증번호를 입력해도 인증이 되어버립니다.
확인 부탁드립니다.

**Comment by unchaptered** [comment]
헉 너무 감사합니다!
해당 부푼 수정 후에 다시 멘션 드리도록 하겠습니다.

**Comment by unchaptered** [comment]
해결되었습니다.
