### ISSUE TITLE
Bug : error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#18]
### 한 일

`2022-09-01 04:00` 에 서버를 재시작하고 나니까 시작되었습니다.

### 에러 내용

```cmd
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (프로젝트-경로\node_modules\jwa\index.js:152:45)
    at Object.jwsSign [as sign] (프로젝트-경로\project\node_modules\jws\lib\sign-stream.js:32:24)
    at Object.module.exports [as sign] (프로젝트-경로\project\node_modules\jsonwebtoken\sign.js:204:16)
    at JwtProvider.signAccessToken (프로젝트-경로\project\dist\modules\providers\jwt.provider.js:33:23)
    at AuthService.<anonymous> (프로젝트-경로\project\dist\routes\services\auth.service.js:125:56)
    at step (프로젝트-경로\project\dist\routes\services\auth.service.js:44:23)
    at Object.next (프로젝트-경로\project\dist\routes\services\auth.service.js:25:53)
    at fulfilled (프로젝트-경로\project\dist\routes\services\auth.service.js:16:58) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

### 조치 사항

Provider 가 문제인가 싶어서,, 다음 처럼 그냥 값을 넣어봤더니 역시 동일한 에러가 발생했습니다.

```cmd
jwt.sign({}, 'secretKey', {
    algorithm: 'RS512'
});
```
[Please tutorial how to fix "error:0909006C:PEM routines:get_name:no start line" with algorithm: "RS256"](https://github.com/auth0/node-jsonwebtoken/issues/642)

### 환경 설정

```cmd
OS:
Node: 16.15.1(unchpatered) 16.13.1(axisotherwise)
npm : 8.1.1(all)
```

**Comment by unchaptered** [comment]
> 에러 발생한 TS 프로젝트 : https://github.com/cupicks/cupicks-be/blob/develop/package.json
> 에러 없는 JS 프로젝트 : https://github.com/CloneCoding-Pinterest/PinterestBE/blob/main/package.json

### 조치사항 3

두 프로젝트의 차이점인 ***typescript 쪽의 문제일까*** 싶어서 jsonwebtoken 을 설치하면 package-lock.json 에 같이 설치되는 `@types/jsonwebtoken` 을 명시적으로 설치해줘도 에러가 해결되지 않았습니다.

설치한 버전 :  `"@types/jsonwebtoken": "^8.5.9"`

**Comment by unchaptered** [comment]
> 에러 발생한 TS 프로젝트 : https://github.com/cupicks/cupicks-be/blob/develop/package.json
> 에러 없는 JS 프로젝트 : https://github.com/CloneCoding-Pinterest/PinterestBE/blob/main/package.json

### 조치사항 4

정확히 모르겠지만 ***종속성 버전*** 의 문제라면, 현재 develop 브런치에 있는 프로젝트를 그대로 받아와서 `npm ci` 를 통해서 실행 시켜도 에러가 떠야곘다고 생각했습니다.

**Comment by axisotherwise** [comment]
### 한 일
타입스크립트 환경에서 jsonwebtoken 라이브러리 메서드 관련 에러 해결

### 에러 내용
```cmd
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (C:\Users\thela\Desktop)
    at Object.jwsSign [as sign] (C:\Users\thela\Desktop)   2:24)
    at module.exports (C:\Users\thela\Desktop)      
    at Object.<anonymous> (C:\Users\thela\Desktop)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\thela\Desktop)  
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\thela\Desktop)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```
jsonwebtoken 라이브러리를 사용하여 토큰 발급 sign 메서드 사용 시 위와 같은 에러가 발생하였습니다.
자바스크립트 환경에서 정상적으로 작동하였지만 타입스크립트 환경에서 sign 메서드로 토큰을 발급할 수가 없었습니다.
에러 "PEM" 키워드를 중점적으로 찾아보니 양방향 암호화에 알게 되었고 라이브러리에서 자체적으로 지원하는 기능 말고 개발자가 직접 비밀키와 공개키를 사용해서 발급할 수 있는 방법을 알게 되었습니다. 

### 조치 사항
- SSL 환경에서 비밀키와 공개키 생성 후 프로젝트 폴더에서 사용 후 토큰 발급과 해독
1. 비밀키 발급
```ssl
genrsa -des3 -out private.pem 2048
```
<img width="160" alt="비밀키" src="https://user-images.githubusercontent.com/94421127/187842641-981bbc04-5735-482f-ac92-5302ca2915db.png">

2. 공개키 발급
```ssl
rsa -in private.pem -outform PEM -pubout -out public.pem
```
<img width="160" alt="공개키" src="https://user-images.githubusercontent.com/94421127/187842653-565245b9-3050-4c5b-80ea-4cdf10a0332b.png">

3. 프로젝트 루트 경로에 비밀키와 공개키 삽입
![image](https://user-images.githubusercontent.com/94421127/187840337-bc5145d3-5a4d-44e7-ae94-1eec665ed46a.png)
 
4. fs 내장 모듈로 비밀키와 공개키 읽은 후 sign과 verify 메서드에 옵션으로 넣어줌
```typescript
import app from "./app";
import { sign, SignOptions, verify } from "jsonwebtoken";
import fs from "fs";
import path from "path";
//
const privateKey = {
    key: fs.readFileSync(path.join(__dirname, "./private.pem"), "utf8"),
    passphrase: "axis" // 비밀키 발급 시 입력했던 패스워드
};

const publicKey = fs.readFileSync(path.join(__dirname, "./public.pem"), "utf-8");

const payload = {
    id: 1,
    name: "user"
};

const options: SignOptions = {
    algorithm: "RS256",
};

const token = sign(payload, privateKey, options);

const decoded = verify(token, publicKey);
console.log(decoded); // { id: 1, name: 'user', iat: 1662011638 }
```
### 환경 설정

```cmd
OS: window10
Node: 16.15.1(unchpatered) 16.13.1(axisotherwise)
npm : 8.1.2(all)
```

**Comment by unchaptered** [comment]
감사합니다!
해당 부분 반영해서 로그인 로직 수정하였습니다. : )

**Comment by unchaptered** [comment]
> ### 조치 사항 5
> jsonwebtoken 라이브러리를 사용하여 토큰 발급 sign 메서드 사용 시 위와 같은 에러가 발생하였습니다. 자바스크립트 환경에서 정상적으로 작동하였지만 타입스크립트 환경에서 sign 메서드로 토큰을 발급할 수가 없었습니다. 에러 "PEM" 키워드를 중점적으로 찾아보니 양방향 암호화에 알게 되었고 라이브러리에서 자체적으로 지원하는 기능 말고 개발자가 직접 비밀키와 공개키를 사용해서 발급할 수 있는 방법을 알게 되었습니다.

토큰 발행이 안되서 막혀있었는데, 덕분에 빠르게 해결할 수 있어서 너무 감사합니다. 👍👍👍
