### ISSUE TITLE
Bug : rimraf not found

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#183]
### 한 일

다음 자동화 배포를 실행하였습니다.

- PR #182 

### 에러 내용

`2022-09-21 16:20` 경 CodeDeploy 의 AfterInstall 커맨드 실행 단계에서 서버가 죽어버렸습니다.
작성 시점인 `2022-09-21 16:24` 에 식별된 주요 문제점은 다음과 같습니다.

1. ssh -i 를 통한 aws ec2 접속 불가
2. rimraf not found

#### 1. ssh -i 를 통한 aws ec2 접속 불가

```cmd
ssh -i 키주소/키파일.키확장자 사용자명@서버-IP
ssh: connect to host 서버-IP port SSH-포트번호: Connection refused
```

ec2 는 정상적으로 가동 중이 었기 떄문에, 일단 aws console 을 통해서 ec2 인스턴스에 접근해서 문제를 해결하고 서버 재가동을 실행했습니다.

이후, 다시 정상적으로 ssh 접속이 활성화되었습니다.

#### 2. rimraf not found

ubuntu 에서 다음과 같은 ***에러*** 가 식별되는데, 아마도 ubuntu@20.04 에서 해당 명령어가 없는 것 같습니다.

```cmd
/tmp/prebuild-난수값.sh: 1: rimraf: not found
```

다음과 같이 ***./node_modules/rimraf/bin.js***  구문을 추가했습니다.

```json
"rimraf": "./node_modules/rimraf/bin.js",
```

#### 3. tsconfig.build.json not found

`.github/workflows/auto.deploy.yml` 안에 `step - Zin File` 안에 ./tsconfig.build.json 을 포함시켜야 했습니다.

- 수정 전
run: zip -r ${{github.event.pull_request.timestamp}}_server.zip .github/workflows ./src ./scripts ./appspec.yml ./gitignore ./package.json ./package-lock.json ./tsconfig.json

- 수정 후
run: zip -r ${{github.event.pull_request.timestamp}}_server.zip .github/workflows ./src ./scripts ./appspec.yml ./gitignore ./package.json ./package-lock.json ./tsconfig.build.json ./tsconfig.json

### 조치 사항

현재 진행 중입니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
확인했습니다!

**Comment by unchaptered** [comment]
모든 문제가 해결되었습니다.
