### ISSUE TITLE
Reqeust : nodemon.json 을 이용한 tsc 호출

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#193]
### 제안사항

@axisotherwise 

package.json

```json
"dev": "nodemon"
```

nodemon 의 설정파일인 nodemon.json 의 exec 인자를 이용하여 tsc 를 사용할 수 있습니다.

```json
{
    "watch": [
        "src"
    ],
    "ignore": [
        "node_modules"
    ],
    "ext": "ts,mjs,js,json,graphql",
    "exec": "tsc -p tsconfig.json && cross-env NODE_ENV=dev node \"dist/server.js\"",
    "legacyWatch": true
}
```

위와 같이 구성을 하면, nodemon 이 src/* 를 감지하고 다음의 단계를 수행합니다.

1. tsc 를 통한 빌드
2. node 를 통한 실행

### 퍼포먼스 측정

- nodemon 을 이용한 빌드는 10회 평균 7.59 초 가 나왔습니다.
- tsc-watch 를 이용한 빌드는 10회 평균 4.12 초가 나왔습니다.

현재 실행 중인 환경이 노트북인 점을 감안해서 tsc-watch 에 대한 빌드 성능의 편차가 큽니다.
하지만 그럼에도 불구하고 2 배의 성능 차이가 나는 것은 끔찍한 것 같습니다.

### 결론

- Issue #137
- Issue #138
- Issue #181

개발 환경에서는 tsc-watch 를 쓰는 것이 nodemon 보다는 나은 것 같습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
덕분에 **tsc-watch** 와 **nodemon** 성능 차이에 대해 너무나 명확하게 이해했습니다!

- https://stackoverflow.com/questions/38276862/is-there-a-way-to-use-npm-scripts-to-run-tsc-watch-nodemon-watch

**Comment by unchaptered** [comment]
> 덕분에 **tsc-watch** 와 **nodemon** 성능 차이에 대해 너무나도 명확하게 이해했습니다. 감사합니다!
> 
> * https://stackoverflow.com/questions/38276862/is-there-a-way-to-use-npm-scripts-to-run-tsc-watch-nodemon-watch

설명을 덧붙이자면,

nodemon 은 기본적으로 `파일 추적 및 재실행` 을 담당하고 있습니다.
tsc-watch 는 위 기능에 덧붙여서 `파일 빌드` 를 하고 있습니다.

따라서, typescript 환경에서 nodemon 을 사용하려면 번들러가 필요하고 튜닝이 완료된 tsc 를 사용하려고 했으나, 역시 성능적인 열화가 심한 것 같았습니다. 아마도 내부적인 프로세스 차이이지 않을까 싶습니다.

아래는 가설이며 입증되지는 않았습니다.

### tsc-watch

1. 파일 감지
2. 파일 번들링 (변경된 파일)
3. 파일 실행

### nodemon

1. 파일 감지
2. 파일 번들링 (전체 파일) - 사실상 tsc 가 독립실행 되고 있지 않나...
3. 파일 실행
