### ISSUE TITLE
Bug : Like 기능 isLiked Patch 버그

### ISSUE THREAD

**Issue by cmun2** [cupicks/cupicks-be#195]
### 한 일
Main Page라이크를 누르면 isLiked가 false일때 빈 하트가 있고 isLiked가 true일때 꽉 찬 하트가 보이도록 조건부 렌더링을 FE에서 설정했습니다. 

### 에러 내용
Main페이지에서 라이크 버튼을 누른 이후에도 isLiked가 false로 출력되는 버그가 보입니다.

![image](https://user-images.githubusercontent.com/66786557/191912491-23295cb9-e899-46ed-86f6-995eb5523d93.png)

**Comment by axisotherwise** [comment]
다음 이슈가 반영되어 1.3.52 버전으로 배포되었습니다!

- Issue #196
