### ISSUE TITLE
Reqeust : `best_recipe_ranking` 테이블 관련

### ISSUE THREAD

**Issue by axisotherwise** [cupicks/cupicks-be#211]
### 제안사항

@unchaptered 

다음 이슈와 관련된 내용입니다.
- Issue #203 

### 제안 하고 싶은 내용

1. 현재 **_best_recipe_ranking_** 테이블의 **Insert** 쿼리는 다음과 같습니다.
```sql
INSERT INTO best_recipe_ranking
    (ranking, recipe_id, start_date, end_date, category)
VALUES
    ("등수", "레시피 아이디, "시작일", "종료일", "weekly")
```
<br>

2. _**베스트 레시피의 1~3등**_ 을 추출해 **Insert** 쿼리를 시도하였는데 다음과 같은 **에러**가 출력되었습니다.
```cmd
sql: '\n' +
  '            INSERT INTO best_recipe_ranking\n' +
  '                (ranking, recipe_id, start_date, end_date, category)\n' +
  '            VALUES\n' +
  "                (1, 19, '2022-09-19 09:19:40', '2022-09-25 09:19:40', 'weekly')\n" +
  '        ',
sqlState: 'HY000',
sqlMessage: "Check constraint 'best_recipe_ranking_chk_1' is violated."
``` 
<br>

3. _**Check**_ 와 **_violated_** 키워드를 바탕으로 검색해본 결과 **ranking** 컬럼의 기준에 부합하지 않아 발생하는 **에러** 로 생각합니다. 현재 설정돼있는 **ranking** 컬럼의 **_CHECK_** 조건은 다음과 같으며 **_3 이상_** 의 수만 입력이 가능한 상태입니다.
```sql
ranking             INT             NOT NULL    CHECK (ranking >=3 AND ranking > 1)
```
<br>

4. 베스트 레시피의 1~3등 을 **Insert** 하려면 **_best_recipe_ranking_** 테이블 **ranking** 컬럼이 다음과 같이 수정되어야 할 거 같습니다.
```sql
ranking             INT             NOT NULL    CHECK (ranking <=3 AND ranking >= 1)
```

### 환경 설정
```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
@axisotherwise 

헉 맞네요.
`sql/*.sql` 파일들 전부 해당 방향으로 수정하면 될 것 같습니다!!
