### ISSUE TITLE
Reqeust : 테스트 코드 폴더 구조

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#23]
### 제안사항

@axisotherwise 

Layer 테스트 보다 일단 Provider 테스트 들이 훨씬 쉽고 용이해서 미리 경험해보는 것이 좋은 것 같은데.
1차 기능 구현 종료 되면 ***테스트 코드*** 작성도 간단한 부분만 바로 진행해보는 것은 어떨까 라는 생각이 듭니다.

테스트 코드를 당장 작성하지는 않더라도 기본적인 ***폴더 구조*** 를 나누고 간단하게 README.md 로 코멘트 정도 달아둘까 하는데 괜찮을까요?

괜찮으시다면 폴더 구조 나눠놓고 설명 따로 올려두겠습니다!

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
네 공급자 테스트 코드 좋은 거 같아요. 확인했습니다~

**Comment by unchaptered** [comment]
> 네 공급자 테스트 코드 좋은 거 같아요. 확인했습니다~

넵, 그러면 기본 폴더 구조 하고 폴더 구조에 대한 가이드만 잡고 바로 PR 띄우겠습니다.

**Comment by unchaptered** [comment]
> 네 공급자 테스트 코드 좋은 거 같아요. 확인했습니다~

완료했습니다!
