### ISSUE TITLE
Reqeust : 응답 데이터 형식 타입 지정 여부

### ISSUE THREAD

**Issue by axisotherwise** [cupicks/cupicks-be#233]
### 제안사항

@unchaptered 

응답 데이터에 **_Dto_** 와 **_Query_** 의 리턴값이 들어가야 하는 경우 응답 데이터에 대한 **_타입_** 지정 여부

제안 하고 싶은 내용

1. 다음은 **_코멘트 전체 조회_** (GET /api/comments?recipeId=""&page""&couint"") 에 전체 **응답 데이터 형식** 입니다.
```typescript
{
   isSuccess: true,
   message: '댓글 전체 조회에 성공했습니다.',
   commentList: [{
      userId: 1234,
      nickname: '유저 닉네임',
      userImageUrl: "http://",                                    
      userResizedUrl: "리사이징 URL",                              
      recipeId: 1234,
      commentId: 12354,
      imageUrl: 'http://',
      recizedUrl: ‘리사이징 URL’,
      comment: '이것은 댓글입니다.',
      createdAt: '2022-08~~' // Date 양식
      updatedAt: '2022-08~~' // Date 양식
   }]
}
```
<br>

2. **_Dto_** 를 통해 얻을 수 있는 값은 다음과 같습니다.
```typescript
    userId: commentDto.userId,
    nickname: commentDto.nickname,
    recipeId: commentDto.recipeId,
    commentId: commentId,
    comment: commentDto.comment,
    imageUrl: commentDto.imageUrl,
    resizedUrl: commentDto.resizedUrl,
```
<br>

3. **_Token Payload_** 를 통해 얻을 수 있는 값은 현재 **userId**, **nickname** 이며 사용자의 **프로필 이미지** 는 알 수가 없으므로 **_Query_** 문을 통해 다음과 같이 **userImageUrl**, **userResizedUrl** 을 가져올 수 있습니다.
```typescript
    userImageUrl: findUserById.imageUrl,
    userResizedUrl: findUserById.resizedUrl,
```
<br>

반환해야 하는 응답 데이터 의 **_타입_** 이 지정되지 않았을 경우 문제가 발생하진 않지만 추후 **_테스트 코드_** 작성을 위해 타입을 지정해 줘야 할지 이 부분 의견 나누면 좋을 거 같습니다!

### 환경 설정
```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
확인했습니다!
저녁에 회의 시간에 한 번 이야기 하면 좋을 것 같네요~~

**Comment by unchaptered** [comment]
> @axisotherwise , 해당 이슈는 오랜 시간 논의되지 않아서 닫아두겠습니다.
