### ISSUE TITLE
Reqeust : 코멘트 삭제/업데이트 기능 관련

### ISSUE THREAD

**Issue by axisotherwise** [cupicks/cupicks-be#61]
### 제안사항
@unchaptered 

제안 하고 싶은 내용
### **제안 1.**
<img width="641" alt="1번 사항" src="https://user-images.githubusercontent.com/94421127/188283900-0311bf39-ed9c-4b9b-a1d1-2b9a45b3391f.PNG">
한글 파일 이름의 이미지가 Bucket 에 저장될 경우 문자열 파싱 에러가 발생하였습니다.
<br>
<br>
      
**생각해본 해결책**
서버와 클라이언트에서 파일에 한글 이름을 제한하는 유효성 검사를 추가하는 방법이 있을 거 같습니다.

### **제안 2.**
코멘트 삭제/업데이트 요청 시 데이터베이스에도 삭제/업데이트와 동시에 Bucket에 저장돼있는 이미지도 삭제/업데이트를 해야 할 거 같습니다.

<img width="114" alt="2번 사항" src="https://user-images.githubusercontent.com/94421127/188284079-94986b65-665b-4cc2-be7f-4a417b9ce88f.PNG">

**생각해본 해결책**
코멘트 삭제/업데이트 요청 시 바디나 쿼리 부분에 이미지 Bucket 주소를 받아야 할 거 같습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
음,,, 한글 파일을 못 보내게 된다는게 조금 그런 것같은데, 파일명을 사용안하고 다름 난수값을 생성해서 넣는 것은 안될까요?

**Comment by axisotherwise** [comment]
> 음,,, 한글 파일을 못 보내게 된다는게 조금 그런 것같은데, 파일명을 사용안하고 다름 난수값을 생성해서 넣는 것은 안될까요?

그럼 UUID를 활용해 보는 건 어떨까요??
https://www.npmjs.com/package/uuid

**Comment by unchaptered** [comment]
> > 음,,, 한글 파일을 못 보내게 된다는게 조금 그런 것같은데, 파일명을 사용안하고 다름 난수값을 생성해서 넣는 것은 안될까요?
> 그럼 UUID를 활용해 보는 건 어떨까요?? https://www.npmjs.com/package/uuid

좋은 것 같습니다. 저도 ***email 인증 과정*** 에서 고유값으로 쓸 문자열이 필요한데, 내일 시간 정해서 한 번 같이 작업해보면 좋을 것 같습니다.

**Comment by axisotherwise** [comment]
다음 이슈가 반영되었습니다.

- Issue #177
