### ISSUE TITLE
Reqeust : user, user_detail, user_refresh_token 테이블 병합

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#66]
### 한 일

- Issue #62 

위 게시글을 참고해주세요.

해당 회의 과정에서 ***user, user_detail, user_refresh_token*** 테이블을 병합하는 내용이 나왔습니다. 또한 ***기술 피드백*** 에 대한 내용이 반영되어 기능 수정이 진행되었습니다.
이 ***[문서](https://www.notion.so/3-_-4d96ee29733c43c59e63cc99af49ef74)*** 에 따라서 수정해주세요.

- PR #67 

***user, user_detail, user_refresh*** 테이블을 병합해서 다음으로 변경했습니다.

```sql
CREATE TABLE IF NOT EXISTS user (
    user_id         INT             NOT NULL    PRIMARY KEY AUTO_INCREMENT,
    email           VARCHAR(20)     NOT NULL    UNIQUE,
    nickname        VARCHAR(10)     NOT NULL    UNIQUE,
    password        VARCHAR(255)    NOT NULL,
    image_url       VARCHAR(255)    NULL,
    refresh_token   VARCHAR(1000)   NULL,
    created_at      DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP
);
```

또한 기존의 메서드에 ***@depreacted*** 인자 혹은 네이밍 끝에 ***Legacy*** 를 붙여서 제거 예정 메서드를 표기하고 새 메서드로 교체하였습니다.

### 에러 내용

```cmd
에러 내용
```

### 조치 사항

만약 조치한 것이 있거나 구글링한 게 있다면, ...

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
작성해 주신 이슈 내용에 따라 ERD 수정하도록 하겠습니다.
