### ISSUE TITLE
Bug : trigger. Configuration is ambiguously defined.

### ISSUE THREAD

**Issue by axisotherwise** [cupicks/cupicks-be#78]
### 에러 내용
lambda 함수 trigger 추가 시 에러가 발생하였습니다.
<img width="628" alt="중복 트리거 오류" src="https://user-images.githubusercontent.com/94421127/188611593-8b16cbf4-7019-4280-be7c-0e3b93e82e74.PNG">

### 조치 사항
<img width="1152" alt="트리거 해결 2" src="https://user-images.githubusercontent.com/94421127/188612032-d1116ecb-5b44-4ef9-9ef8-67e8fad34f7d.png">
에러 키워드로 검색 한 결과 기존에 등록한 trigger와 새로 등록한 trigger가 충돌하여 발생한 문제였습니다.

![image](https://user-images.githubusercontent.com/94421127/188612749-2fe250e2-f2e1-4622-97ed-23995150c9cf.png)
Bucket 속성 이벤트 알림탭에서 이전에 등록한 trigger를 삭제하면 더 이상 충돌이 일어나지 않습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
오,,, 엄청 멋있네요,,,
고생하셨습니다,,
저는 람다가 ***express*** 에서 호출 하는 것인 줄 알았는데, S3 의 ***이벤트 리스너*** 가 있는지 몰랐네요.

**Comment by axisotherwise** [comment]
**Bugfix** 하여 해당 이슈는 **Close** 하겠습니다!
