### ISSUE TITLE
Reqeust : Dto 의 슈퍼 클래스인 RequestQueryExtractor 제안

### ISSUE THREAD

**Issue by unchaptered** [cupicks/cupicks-be#91]
## 제안사항

@axisotherwise

현재 저희 도메인 전체에서 ***req.query***  안에서 매개변수를 꺼내야 하는 경우가 너무 많습니다.
그런데, req.query 안에서 값을 꺼내면 다음과 같은 타입으로 나오는 이슈가 있었습니다.

```typescript
const nickname: string | string[] | ParsedQs | ParsedQs[] | undefined = req.query.nickname;
```

이 친구를 string 으로 변환하려면 다음과 같이 일정한 조건문 분기를 지나게 해야 합니다.

```typescript
const nickname: string | string[] | ParsedQs | ParsedQs[] | undefined = req.query.nickname;

const transformToString = async (value: string | string[] | ParsedQs | ParsedQs[] | undefined) => {
    if (value === undefined) throw new Error("Query 의 ??? 은 undefined 이여서는 안됩니다.");
    else if (typeof value === "string") return value;
    else throw new Error("Query 의 ??? 의 형태가 이상합니다. ${JSON.stringify(value)}");
}

const afterNickname: string = transformToString(nickname);
```

이 함수를 Dto 안에 넣어서 적용시킨 예시 중 하나가 ConfirmEmailDto 입니다.
아래 Dto 에서는 ***함수 추출하기*** 를 통해서 반복적되는 코드를 줄일 수 있었습니다.

```typescript
export interface IConfirmNicknameDto {
    email: string;
    nickname: string;
}

export class ConfirmNicknameDto implements IBaseDto, IConfirmNicknameDto {
    email: string;
    nickname: string;

    constructor({
        email,
        nickname,
    }: {
        email: string | string[] | ParsedQs | ParsedQs[] | undefined;
        nickname: string | string[] | ParsedQs | ParsedQs[] | undefined;
    }) {
        this.email = this.validateType(email);
        this.nickname = this.validateType(nickname);
    }

    private validateType(value: string | string[] | ParsedQs | ParsedQs[] | undefined): string {
        if (value === undefined) throw new Error("Query 의 ??? 은 undefined 이여서는 안됩니다.");
        else if (typeof value === "string") return value;
        else throw new Error("Query 의 ??? 의 형태가 이상합니다. ${JSON.stringify(value)}");
    }

    getJoiInstance(): ObjectSchema<ConfirmNicknameDto> { /* 해당 메서드는 주제 논외이므로 생략 */ }
}
```

해당 메서드는 모든 Dto 에 추가해서 사용할 수 있지만,  다음과 같은 치명적인 문제점을 가지고 있습니다.

> ✔ 1. ***프론트엔드 개발자*** 혹은 ***사용자*** 에게 어떤 값이 누락되었는지 알려줄 수 없다.
> ✔ 2. 어떤 Dto 는 ***validateType*** 가지고 있고, 어떤 Dto 는 가지고 있찌 않기 때문에, 통일성이 없다.

### ✔ 1. 따라서 validateType 을 다음과 같이 변경하면, ***1번 문제*** 를 해결할 수 있습니다.

```typescript
private validateType<T extends "email" | "nickname">(value: string | string[] | ParsedQs | ParsedQs[] | undefined, target: T): string {
    if (value === undefined) throw new Error(`Query 의 ${target} 은 undefined 이여서는 안됩니다.`);
    else if (typeof value === "string") return value;
    else throw new Error(`Query 의 ${target} 의 형태가 이상합니다. ${JSON.stringify(value)}`);
}
```

위 방식처럼 짠 ***지네릭 메서드*** 는 다음과 같이 사용될 수 있습니다.
메서드 선언부에서 등록되어있는 ***지네릭 타입*** 이 'email' 과 'nickname' 밖에 없으므로, 실제로 사용할 때에도 두 문자열만 넣어줄 수 있습니다.

![image](https://user-images.githubusercontent.com/86306802/188700215-13355376-34be-433a-bbdd-075039a1175d.png)

### ✔ 2. ***2번 문제*** 를 해결하기 위해서는 모든 Dto 의 슈퍼(부모) 클래스를 만들어서 해결할 수 있습니다.

```typescript
class RequestQueryExtractor {

    protected validateType<T>(value: string | string[] | ParsedQs | ParsedQs[] | undefined, target: T): string {
        if (value === undefined) throw new Error(`Query 의 ${target} 은 undefined 이여서는 안됩니다.`);
        else if (typeof value === "string") return value;
        else throw new Error(`Query 의 ${target} 인자의 형태가 이상합니다. ${JSON.stringify(value)}`);
    }

}
export class ConfirmNicknameDto extends RequestQueryExtractor implements IBaseDto, IConfirmNicknameDto { 
   /* 나머지는 동일 */
}
```

다만, 이 친구를 그대로 상속 시킬 경우에는 literal type 이 아니라 ***string 타입*** 으로 나오게 됩니다.

![image](https://user-images.githubusercontent.com/86306802/188700931-7a511087-3651-4fb2-b1b2-0054c6d1767e.png)

그 이유는 지네릭 메서드가 선언되는 시점에 T 가 ***와일드 카드*** 처럼 사용되고 있기 때문입니다.
따라서 지네릭 타입의 선언 부분이 ***메서드*** 가 아니라 ***클래스*** 단위에 위치해야, 클래스를 상속 받는 시점에 ***지네릭 타입***을 결정할 수 있게 됩니다.

> 풀어서 설명하자면,
> 메서드의 선언부에 위치한 ***지네릭 타입*** 은 해당 메서드를 소유한 클래스가 그 타입을 결정짓게 되며,
> 클래스의 선언부에 위치한 ***지네릭 타입*** 은 _생성자 호출 시점 _ 혹은 자식 클래스가 그 타입을 결정 짓게 됩니다.

따라서, 다음과 같이 ***RequestQueryExtractor*** 을 변경하면, ...

```typescript
class RequestQueryExtractor<T> {

    protected validateType(value: string | string[] | ParsedQs | ParsedQs[] | undefined, target: T): string {
        if (value === undefined) throw new Error(`Query 의 ${target} 은 undefined 이여서는 안됩니다.`);
        else if (typeof value === "string") return value;
        else throw new Error(`Query 의 ${target} 인자의 형태가 이상합니다. ${JSON.stringify(value)}`);
    }

}
export class ConfirmNicknameDto extends RequestQueryExtractor<'email' | 'nickname'> implements IBaseDto, IConfirmNicknameDto {
    email: string;
    nickname: string;

    constructor({
        email,
        nickname,
    }: {
        email: string | string[] | ParsedQs | ParsedQs[] | undefined;
        nickname: string | string[] | ParsedQs | ParsedQs[] | undefined;
    }) {
        super();
        this.email = this.validateType(email, 'email');
        this.nickname = this.validateType(nickname, 'nickname');
    }
}
```

다시, 메서드를 호출하는 시점에서도 ***literal type*** 이 나오게 됩니다.

![image](https://user-images.githubusercontent.com/86306802/188702208-e8c7b515-316d-4492-80af-aa9cd436ab45.png)

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by axisotherwise** [comment]
제안해 주신 `RequestQueryExtractor` 를 적용하여 쿼리 타입의 Dto 추가 완료했습니다.

**Comment by unchaptered** [comment]
## 추가 제안사항 A

@axisotherwise 

- 기존의 RequestQueryExtractor 의 메서드 이름 변경

기존의 메서드 이름은 validateType 인데 해당 부분이 가독성이 떨어지는 것 같습니다.
결국 queryString 인자에서 단일 string 을 꺼내는 것이므로 getStringFromQuery 가 어떤지 의견 여줘보고 싶습니다.

**Comment by unchaptered** [comment]
## 추가 제안사항 B

@axisotherwise 

- RequestQueryExtractor 의 메서드 추가

현재, query 에서 값을 꺼낼 때를 위해서 다음의 2 메서드가 지원되고 있습니다.

1. validateType : **필수값** 인 stirng 을꺼내기 위한 메서드
2. validateTypeOrUndefined : **선택값** 인 string | undefined 을 꺼내기 위한 메서드

이에, 다음의 메서드를 추가하는 것을 건의합니다.

1. string[] 을 추출하는 메서드
2. string[] | undefined 을 추출하는 메서드
3. 중복이 배제된 string[] (사실상 Set) 을 추출하는 메서드
4. 중복이 배제된 string[] | undefined 을 추출하는 메서드

**Comment by unchaptered** [comment]
@axisotherwise 
기능 구현을 위해서 임시 반영 해두었습니다.

**Comment by axisotherwise** [comment]
남겨주신 제안 사항 A 와 B 확인하였습니다. 오늘 시간 정해서 B 에 대해서 애기해보면 좋을 거 같습니다~!

**Comment by unchaptered** [comment]
> 해당 이슈는 모두 반영되었습니다.
