### ISSUE TITLE
Request : Lambda 호출 관련

### ISSUE THREAD

**Issue by axisotherwise** [cupicks/cupicks-be#99]
### 내용
![image](https://user-images.githubusercontent.com/94421127/189014966-281ca2ff-6b26-4605-8ad4-b7611e2497a1.png)
현재 사용자 프로필과 코멘트 작성 시 사용하는 이미지 2가지 종류의 이미지를 **s3 Bucket**에 경로를 구분하여 저장하고 있는데요.

![image](https://user-images.githubusercontent.com/94421127/189015066-9d3ec5fa-78d2-450b-b9a0-83f864408a33.png)
현재 Lambda가 실행하는 함수의 리사이징 코드는 프로필 이미지이고 다른 하나인 코멘트 이미지를 다른 사이즈로 리사이징 하려고 한다면 **Bucket**에 저장 경로를 구분하지 않고 하나의 폴더에 저장하고 하나의 **트리거(Prefix)** 를 사용해  함수 내에서 프로필과 코멘트를 구분해 분기 처리를 하는 방법과 하나의 Lambda 를 더 추가하여 프로필 이미지와 코멘트 이미지를 각각 실행하게 하는 방법입니다.

### 제안 사항
알아본 결과 2가지의 방법이 있는 거 같습니다. 둘 중 비용은 동일할 거 같은데 프로필과 코멘트 이미지의 리사이징이 동시에 일어날 경우도 고려해야 할 거 같아서 어떠한 방법을 선택해야 조금 더 나은 성능을 기대할 수 있을지 기술 피드백이 필요할 거 같습니다.

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by unchaptered** [comment]
금일 진행된 2차 기술 피드백을 참고해주세요 🎈

- Issue #107

**Comment by axisotherwise** [comment]
#133
위 이슈를 반영 할 예정입니다.
